apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: $LLDAP_NAME
  name: $LLDAP_NAME-data
  namespace: $LLDAP_NAMESPACE
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
