kind: Secret
apiVersion: v1
metadata:
  labels:
    app: lldap
  name: lldap-credentials
  namespace: lldap
data:
  base-dn: ZGM9ZXhhbXBsZSxkYz1jb20=
  lldap-jwt-secret: dGhpc2lzYWRlbW9wYXNzd29yZA==
  lldap-ldap-user-pass: ZGVtb2FkbWlucGFzc3dvcmQ=
type: Opaque
